### ISSUE TITLE
Can't start Selendroid Serer in 1.4.0.0

### ISSUE THREAD

**Issue by EthanJiang** [appium/appium-dot-exe#151]
Just download the latest version AppiumForWindows 1.4.0.0 and try to start the Appium and  Selendroid serer.

The Appium Server can be started successfully.
The Selendroid Server can not be started. 

The error: 

> info: [debug] Screen already unlocked, continuing.
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5556 shell "am instrument -e main_activity 'com.test.myApp.RootActivity' com.test.myApp.selendroid/io.selendroid.server.ServerInstrumentation"
> info: [debug] Making http request with opts: {"url":"http://localhost:4444/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: 
..........
{"url":"http://localhost:4444/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:4444/wd/hub/status","method":"GET"}
> error: Could not pre-launch appium: Error: Waited 20 secs for selendroid server and it never showed up

Thanks

**Comment by Astro03** [comment]
@penguinho is this the same issue you are having and didn't update?

**Comment by penguinho** [comment]
no, the issue I was having was chromedriver related

**Comment by EthanJiang** [comment]
I am planning to update my local AppiumServer from 1.2.4.1 to a new stable version. 
It seems version 1.4.0.0 can't work well with selendroid. 
So when will you release next version? 
or Which recent version is more stable ?

Any one can help? 
Thanks

**Comment by Astro03** [comment]
how was the previous version? I dont use selendroid so i haven't tested it.

**Comment by EthanJiang** [comment]
I download the 1.3.7.0 / 1.3.7.1 / 1.3.7.2  / 1.4.0.0 
all get the same error:

> error: android.util.AndroidException: INSTRUMENTATION_FAILED: com.test.testapp.selendroid/io.selendroid.server.ServerInstrumentation
> 
> 	at com.android.commands.am.Am.runInstrument(Am.java:616)
> 
> 	at com.android.commands.am.Am.run(Am.java:118)
> 
> 	at com.android.commands.am.Am.main(Am.java:81)
> 
> 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
> 
> 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:235)
> 
> 	at dalvik.system.NativeStart.main(Native Method)
> info: [debug] Cleaning up appium session

Thanks

**Comment by EthanJiang** [comment]
> Starting Node Server
> warn: Appium support for versions of node < 0.12 has been deprecated and will be removed in a future version. Please upgrade!
> info: [debug] Starting Appium in pre-launch mode
> info: Pre-launching app
> info: [debug] Using local app from command line: D:\Android\APKSource\ApiDemos-debug.apk
> info: [debug] Creating new appium session dbceea2a-72d0-4109-aae2-395b3ddaba4e
> info: [debug] Starting selendroid server
> info: [debug] Getting Java version
> info: Java version is: 1.7.0_07
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from C:\Android\esdk\sdk\platform-tools\adb.exe
> info: [debug] Checking whether selendroid is built yet
> info: [debug] Selendroid server exists!
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Checking whether app is actually present
> info: [debug] Trying to find API16 emulator
> info: [debug] Getting connected emulators
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe devices
> info: [debug] 0 device(s) connected
> info: [debug] 0 emulator(s) connected
> info: [debug] Launching Emulator with AVD API16, launchTimeout 120000ms and readyTimeout 120000ms
> info: [debug] Checking whether emulator is present
> info: [debug] Using emulator from C:\Android\esdk\sdk\tools\emulator.exe
> info: [debug] Trying to find API16 emulator
> info: [debug] Getting connected emulators
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe devices
> info: [debug] 0 device(s) connected
> info: [debug] 0 emulator(s) connected
> error: Unable to start Emulator: HAX is working and emulator runs in fast virt mode
> 
> info: [debug] Trying to find API16 emulator
> info: [debug] Getting connected emulators
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe devices
> info: [debug] 0 device(s) connected
> info: [debug] 0 emulator(s) connected
> info: [debug] Trying to find API16 emulator
> info: [debug] Getting connected emulators
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe devices
> info: [debug] 0 device(s) connected
> info: [debug] 0 emulator(s) connected
> info: [debug] Trying to find API16 emulator
> info: [debug] Getting connected emulators
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe devices
> info: [debug] 0 device(s) connected
> info: [debug] 0 emulator(s) connected
> info: [debug] Trying to find API16 emulator
> info: [debug] Getting connected emulators
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe devices
> info: [debug] 0 device(s) connected
> info: [debug] 0 emulator(s) connected
> info: [debug] Trying to find API16 emulator
> info: [debug] Getting connected emulators
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe devices
> info: [debug] 0 device(s) connected
> info: [debug] 0 emulator(s) connected
> info: [debug] Trying to find API16 emulator
> info: [debug] Getting connected emulators
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe devices
> info: [debug] 0 device(s) connected
> info: [debug] 0 emulator(s) connected
> info: [debug] Trying to find API16 emulator
> info: [debug] Getting connected emulators
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe devices
> info: [debug] 0 device(s) connected
> info: [debug] 0 emulator(s) connected
> info: [debug] Trying to find API16 emulator
> info: [debug] Getting connected emulators
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe devices
> info: [debug] 0 device(s) connected
> info: [debug] 0 emulator(s) connected
> info: [debug] Trying to find API16 emulator
> info: [debug] Getting connected emulators
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe devices
> info: [debug] 0 device(s) connected
> info: [debug] 0 emulator(s) connected
> info: [debug] Trying to find API16 emulator
> info: [debug] Getting connected emulators
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe devices
> info: [debug] 0 device(s) connected
> info: [debug] 0 emulator(s) connected
> info: [debug] Trying to find API16 emulator
> info: [debug] Getting connected emulators
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe devices
> info: [debug] 0 device(s) connected
> info: [debug] 0 emulator(s) connected
> info: [debug] Trying to find API16 emulator
> info: [debug] Getting connected emulators
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe devices
> info: [debug] 0 device(s) connected
> info: [debug] 0 emulator(s) connected
> info: [debug] Trying to find API16 emulator
> info: [debug] Getting connected emulators
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe devices
> info: [debug] 0 device(s) connected
> info: [debug] 0 emulator(s) connected
> info: [debug] Trying to find API16 emulator
> info: [debug] Getting connected emulators
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe devices
> info: [debug] 0 device(s) connected
> info: [debug] 0 emulator(s) connected
> info: [debug] Trying to find API16 emulator
> info: [debug] Getting connected emulators
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe devices
> info: [debug] 0 device(s) connected
> info: [debug] 0 emulator(s) connected
> info: [debug] Trying to find API16 emulator
> info: [debug] Getting connected emulators
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: [debug] 1 emulator(s) connected
> info: [debug] Sending telnet command to device: avd name
> info: [debug] Getting running emulator port
> info: [debug] Socket connection to device created
> info: [debug] Socket connection to device ready
> info: [debug] Telnet command got response: API16
> info: [debug] Found emulator API16 in port 5554
> info: [debug] Setting device id to emulator-5554
> info: [debug] Waiting until emulator is ready
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 shell "getprop init.svc.bootanim"
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 150)
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 wait-for-device
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\Android\esdk\sdk\build-tools\android-4.4W\aapt.exe
> info: [debug] Checking if has internet permission from manifest.
> info: [debug] executing cmd: C:\Android\esdk\sdk\build-tools\android-4.4W\aapt.exe dump badging D:\Android\APKSource\ApiDemos-debug.apk
> info: [debug] Rebuilt selendroid server does not exist, inserting modified manifest
> info: [debug] Inserting selendroid manifest
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\Android\esdk\sdk\build-tools\android-4.4W\aapt.exe
> info: [debug] Compiling manifest c:\temp\io.appium.android.apis\AndroidManifest.xml
> info: [debug] Compiling manifest.
> info: [debug] executing cmd: C:\Android\esdk\sdk\build-tools\android-4.4W\aapt.exe package -M c:\temp\io.appium.android.apis\AndroidManifest.xml --rename-manifest-package io.appium.android.apis.selendroid --rename-instrumentation-target-package io.appium.android.apis -I C:\Android\esdk\sdk\platforms\android-21\android.jar -F c:\temp\io.appium.android.apis\AndroidManifest.xml.apk -f
> info: [debug] Compiled manifest
> info: [debug] Inserting manifest, src: D:\Android\Appium\node_modules\appium\build\selendroid\selendroid.apk, dst: c:\temp\selendroid.io.appium.android.apis.apk
> info: [debug] Extracting manifest
> info: [debug] Unzipping c:\temp\io.appium.android.apis\AndroidManifest.xml.apk
> info: [debug] Testing zip archive: c:\temp\io.appium.android.apis\AndroidManifest.xml.apk
> info: [debug] Zip archive tested clean
> info: [debug] Unzip successful
> info: [debug] Writing tmp apk. D:\Android\Appium\node_modules\appium\build\selendroid\selendroid.apk to c:\temp\selendroid.io.appium.android.apis.apk
> info: [debug] Testing new tmp apk.
> info: [debug] Testing zip archive: c:\temp\selendroid.io.appium.android.apis.apk
> info: [debug] Zip archive tested clean
> info: [debug] Moving manifest.
> info: [debug] executing cmd: "C:\Program Files\Java\jdk1.7.0_71\bin\java.exe" -jar D:\Android\Appium\node_modules\appium\node_modules\appium-adb\jars\move_manifest.jar c:\temp\selendroid.io.appium.android.apis.apk c:\temp\io.appium.android.apis\AndroidManifest.xml
> info: [debug] Inserted manifest.
> info: [debug] Checking signed status of c:\temp\selendroid.io.appium.android.apis.apk
> info: [debug] Checking app cert for c:\temp\selendroid.io.appium.android.apis.apk.
> info: [debug] executing cmd: java -jar D:\Android\Appium\node_modules\appium\node_modules\appium-adb\jars\verify.jar c:\temp\selendroid.io.appium.android.apis.apk
> info: [debug] Checking signed status of D:\Android\APKSource\ApiDemos-debug.apk
> info: [debug] Checking app cert for D:\Android\APKSource\ApiDemos-debug.apk.
> info: [debug] executing cmd: java -jar D:\Android\Appium\node_modules\appium\node_modules\appium-adb\jars\verify.jar D:\Android\APKSource\ApiDemos-debug.apk
> info: [debug] App not signed with debug cert.
> info: [debug] Resigning apk.
> info: [debug] executing cmd: java -jar D:\Android\Appium\node_modules\appium\node_modules\appium-adb\jars\sign.jar c:\temp\selendroid.io.appium.android.apis.apk --override
> info: [debug] App already signed.
> info: [debug] Zip-aligning D:\Android\APKSource\ApiDemos-debug.apk
> info: [debug] Checking whether zipalign is present
> info: [debug] Using zipalign from C:\Android\esdk\sdk\build-tools\android-4.4W\zipalign.exe
> info: [debug] Zip-aligning apk.
> info: [debug] executing cmd: C:\Android\esdk\sdk\build-tools\android-4.4W\zipalign.exe -f 4 D:\Android\APKSource\ApiDemos-debug.apk c:\temp\115426-4328-1hfdesr\appium.tmp
> info: [debug] Zip-aligning c:\temp\selendroid.io.appium.android.apis.apk
> info: [debug] Checking whether zipalign is present
> info: [debug] Using zipalign from C:\Android\esdk\sdk\build-tools\android-4.4W\zipalign.exe
> info: [debug] Zip-aligning apk.
> info: [debug] executing cmd: C:\Android\esdk\sdk\build-tools\android-4.4W\zipalign.exe -f 4 c:\temp\selendroid.io.appium.android.apis.apk c:\temp\115426-4328-qr5gvn\appium.tmp
> info: [debug] Rebuilt selendroid apk does not exist, uninstalling any instances of it on device to make way for new one
> info: [debug] Uninstalling io.appium.android.apis.selendroid
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 shell "am force-stop io.appium.android.apis.selendroid"
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 uninstall io.appium.android.apis.selendroid
> info: [debug] App was not uninstalled, maybe it wasn't on device?
> info: [debug] Getting install status for io.appium.android.apis.selendroid
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 16
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 shell "pm list packages -3 io.appium.android.apis.selendroid"
> info: [debug] App is not installed
> info: [debug] Rebuilt selendroid is not installed, installing it
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 install -r "c:\temp\selendroid.io.appium.android.apis.apk"
> info: [debug] Extracting strings for language: default
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 shell "getprop persist.sys.language"
> info: [debug] Current device persist.sys.language: en
> info: [debug] java -jar "D:\Android\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "D:\Android\APKSource\ApiDemos-debug.apk" "c:\temp\io.appium.android.apis" en
> info: [debug] No strings.xml for language 'en', getting default strings.xml
> info: [debug] java -jar "D:\Android\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "D:\Android\APKSource\ApiDemos-debug.apk" "c:\temp\io.appium.android.apis"
> info: [debug] Reading strings from converted strings.json
> info: [debug] Setting language to default
> info: [debug] Not uninstalling app since server not started with --full-reset
> info: [debug] Checking app cert for D:\Android\APKSource\ApiDemos-debug.apk.
> info: [debug] executing cmd: java -jar D:\Android\Appium\node_modules\appium\node_modules\appium-adb\jars\verify.jar D:\Android\APKSource\ApiDemos-debug.apk
> info: [debug] App already signed.
> info: [debug] Zip-aligning D:\Android\APKSource\ApiDemos-debug.apk
> info: [debug] Checking whether zipalign is present
> info: [debug] Using zipalign from C:\Android\esdk\sdk\build-tools\android-4.4W\zipalign.exe
> info: [debug] Zip-aligning apk.
> info: [debug] executing cmd: C:\Android\esdk\sdk\build-tools\android-4.4W\zipalign.exe -f 4 D:\Android\APKSource\ApiDemos-debug.apk c:\temp\115426-4328-1r81n1o\appium.tmp
> info: [debug] MD5 for app is f106608e94bc9c1a18562dee1299c68f
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 shell "ls /data/local/tmp/f106608e94bc9c1a18562dee1299c68f.apk"
> info: [debug] Getting install status for io.appium.android.apis
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 16
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 shell "pm list packages -3 io.appium.android.apis"
> info: [debug] App is not installed
> info: Installing App
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 shell "mkdir -p /data/local/tmp/"
> info: [debug] Removing any old apks
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 shell "ls /data/local/tmp/*.apk"
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 shell rm "/data/local/tmp/fa1da2ae4cd36504b8f266a1afc801da.apk" && rm "/data/local/tmp/selendroid.com.hp.android.printlibtestapp.apk" && rm "/data/local/tmp/selendroid.io.appium.android.apis.apk" && rm "/data/local/tmp/settings_apk-debug.apk" && rm "/data/local/tmp/unlock_apk-debug.apk"
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 push "D:\\Android\\APKSource\\ApiDemos-debug.apk" /data/local/tmp/f106608e94bc9c1a18562dee1299c68f.apk
> info: [debug] Uninstalling io.appium.android.apis
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 shell "am force-stop io.appium.android.apis"
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 uninstall io.appium.android.apis
> info: [debug] App was not uninstalled, maybe it wasn't on device?
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 shell "pm install -r /data/local/tmp/f106608e94bc9c1a18562dee1299c68f.apk"
> info: [debug] Forwarding system:8080 to device:8080
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 forward tcp:8080 tcp:8080
> info: [debug] Pushing settings apk to device...
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 install "D:\Android\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 install "D:\Android\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 shell "dumpsys window"
> info: Unlocking screen
> info: [debug] Screen is locked, trying to unlock
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 16
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 shell "dumpsys window"
> info: [debug] Screen is unlocked, continuing
> info: [debug] executing cmd: C:\Android\esdk\sdk\platform-tools\adb.exe -s emulator-5554 shell "am instrument -e main_activity 'ApiDemos' io.appium.android.apis.selendroid/io.selendroid.server.ServerInstrumentation"
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> error: Could not pre-launch appium: Error: Waited 20 secs for selendroid server and it never showed up
> 
> Node Server Process Ended

**Comment by EthanJiang** [comment]
Do I missing something to setup my environment? 
I have reinstall the latest Android SDK, update the Node.js. but it still does not work.

**Comment by EthanJiang** [comment]
Or should I install selendroid-standalone ?

**Comment by vijay0850** [comment]
@EthanJiang I also had this issues during the beginning of selendroid in appium try this following things any of this may work,
1. setCapabilites --> automation name as selendroid
2. Don't use UI setting just set everything in ur code itself.
3. Try to run selendroid-standalone server manually(u can get this from selendroid site) and then check 
4. Uninstall the app from device and run the test.

I will share my code later, All the best for ur tries :)

**Comment by EthanJiang** [comment]
@vijay0850 Thank you very much. I will try that.

**Comment by EthanJiang** [comment]
New Update, 

This should be a defect in Appium.

Even though the log show "Waited 20 secs for selendroid server and it never showed up" 
but when I manually input "http://localhost:4444/wd/hub/status" in IE, I can get the result: 
        {"value":{"supportedApps":[],"build":{"browserName":"selendroid","version":"0.15.0"},"os":{"arch":"x86","version":"16","name":"Android"},"supportedDevices":[]},"status":0}

Or input "http://localhost:4444/inspector" in IE, I can get the message : "Selendroid Inspector can only be used with an active test session."

If the Selendroid sever donot startup, I should not get the response.

Log
info: [debug] Making http request with opts: {"url":"http://localhost:4444/wd/hub/status","method":"GET"}
info: [debug] Making http request with opts: {"url":"http://localhost:4444/wd/hub/status","method":"GET"}
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Waited 20 secs for selendroid server and it never showed up
info: [debug] Error: Waited 20 secs for selendroid server and it never showed up
    at D:\Android\Appium\node_modules\appium\lib\devices\android\selendroid.js:342:14
    at Request._callback (D:\Android\Appium\node_modules\appium\lib\devices\common.js:121:5)
    at self.callback (D:\Android\Appium\node_modules\appium\node_modules\request\request.js:344:22)
    at Request.emit (events.js:107:17)
    at Request.init (D:\Android\Appium\node_modules\appium\node_modules\request\request.js:591:17)
    at new Request (D:\Android\Appium\node_modules\appium\node_modules\request\request.js:264:8)
    at request (D:\Android\Appium\node_modules\appium\node_modules\request\index.js:50:10)
    at Object.exports.doRequest (D:\Android\Appium\node_modules\appium\lib\devices\common.js:120:3)
    at [object Object].exports.proxyTo (D:\Android\Appium\node_modules\appium\lib\devices\common.js:176:11)
    at [object Object].<anonymous> (D:\Android\Appium\node_modules\appium\lib\devices\android\selendroid.js:337:10)
    at Timer.listOnTimeout (timers.js:110:15)

**Comment by EthanJiang** [comment]
Hello, will we fix this in the next version?
