### ISSUE TITLE
Getting error - Exception in thread "main" io.selendroid.server.common.exceptions.SessionNotCreatedException: An error occurred while resigning the app 'selendroid-test-app-0.16.0.apk'. 

### ISSUE THREAD

**Issue by ejkdeveloper** [appium/appium-dot-exe#158]
HI Team,

This is my first attempt to install seledroid in MAC machine for Android and IOS automation. Currently to test I was referring the configuration steps and provided the below command

CMD: 
java -jar selendroid-standalone-0.16.0-with-dependencies.jar -app selendroid-test-app-0.16.0.apk

but I am facing an error as below. 
NOTE: also I have configured the JAVA_HOME and ANDROID_HOME directory access properly on the.bash_profile and on cd commands they are accessible. SO please clarify.

androiddebugkey
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:53)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.signTestServer(SelendroidServerBuilder.java:296)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:154)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.addToAppsStore(SelendroidStandaloneDriver.java:121)
	... 6 more
Caused by: io.selendroid.standalone.exceptions.ShellCommandException: 
	... 10 more

**Comment by Astro03** [comment]
you're running this on a windows box or a mac box?

**Comment by ejkdeveloper** [comment]
I am running on the MAC 10.10.5

**Comment by Astro03** [comment]
then you are in the wrong channel.

Please open this bug in https://github.com/appium/appium-dot-app
